Update index.js
js-tasks-ru/jsbasic-20210906-2_pakhara pull request #1
Opened 2021-09-14 09:35 UTC by Nastenka2701

1. Факториал

2021-09-14 09:35 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2021-09-14 20:01 UTC, SinimaWath requested changes

2021-09-14 20:01 UTC, SinimaWath commented on 1-module/1-task/index.js
> +     return n ? n * factorial(n - 1) : 1;
- Давай не использовать в коде var, рассказывал, что он устарел
- Давай перепишем без рекурсии. У нее есть основныя проблема - это возможное переполнение стека(слишком много функции вызванно)

2021-09-14 20:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-09-16 20:14 UTC, SinimaWath commented
Чтобы сдать PR- надо сделать все задачи, которые у тебя добавленны в задачнике

2021-09-17 10:38 UTC, closed without merging